#!/bin/sh
APPDIR=`dirname $0`;
java  -Xmx256M -cp "$APPDIR/src:$APPDIR/bin:/home/andrew/installed/gwt/gwt-linux-1.6.4/gwt-user.jar:/home/andrew/installed/gwt/gwt-linux-1.6.4/gwt-dev-linux.jar:/home/andrew/gwt/gwt-incubator.jar" com.google.gwt.dev.GWTShell -out "$APPDIR/www" "$@" com.mycompany.MyApplication/MyApplication.html;
