package hardcoded.designgridlayout;



/** generated by Evolve */
public class DesignGridLayoutPanel
{

  private test.DesignGridLayoutHandler dd = new test.DesignGridLayoutHandler();
  private javax.swing.JPanel x = new javax.swing.JPanel();

  public DesignGridLayoutPanel()
  {
  }

  public void setSlots()
  {
  }

  public javax.swing.JPanel getPanel_JPanel(Class<?> required)
  {
    return x;
  }

  public void setRows_IRow(test.IRow iface, int index)
  {
    dd.setRows_IRow(iface, index);
  }

  public void cacheProvidedInterfaces()
  {
  }

  public void setRequiredInterfaces()
  {
    dd.setLayout_Container(x);
  }

  public DesignGridLayoutPanel init(boolean children)
  {
    if (children)
    {
      setSlots();
      cacheProvidedInterfaces();
      setRequiredInterfaces();
    }
    dd.afterInit();
    return this;
  }
}
