package bridge;

import com.intrinsarc.backbone.runtime.api.*;

public class Car
// start generated code

// Generated by Evolve, community edition
// This code is licensed under the Affero GPL version 3: http://www.gnu.org/licenses/agpl.html
// The AGPL is an open source license that requires any distributed application to be also available in source form.
// To remove these comments and licensing restrictions, please consider purchasing a commercial version of evolve at http://www.intrinsarc.com

 implements ILifecycle
{
	// attributes
	private int carNo = 0;

	// attribute setters and getters
	public int getCarNo() { return carNo; }
	public void setCarNo(int carNo) { this.carNo = carNo;}

	// required ports
	private bridge.I_move move;
	private bridge.I_access bridge;

	// port setters and getters
	public void setMove(bridge.I_move move) { this.move = move; }
	public void setBridge(bridge.I_access bridge) { this.bridge = bridge; }

// end generated code
        

    Runnable runnit = new Runnable()
    {
	    public void run() {
	      try {
	        while (true) {
	            while (!move.move(carNo));  // not on bridge
	            bridge.enter();
	            while (move.move(carNo));   // move over bridge
	           bridge.leave();
	         }
	      } catch (InterruptedException e){}
	    }
    };

    Thread car;
    
    public void afterInit() {
        car = new Thread(runnit);
        car.start();
    }

    public void beforeDelete() {
        car.interrupt();
    }
}
