package com.mycompany.client.hardcoded;

import com.hopstepjump.backbone.runtime.api.*;

/** generated by Evolve */
public class GWTCustomerWidgetFactory
{
  private Attribute<String> text = new Attribute<String>("Enter full name");
  private Attribute<String> text1 = new Attribute<String>("Enter normal address");
  private Attribute<String> text2 = new Attribute<String>("First:");
  private Attribute<String> text3 = new Attribute<String>("Last");
  private Attribute<String> text4 = new Attribute<String>("Street:");
  private Attribute<String> text5 = new Attribute<String>("Town:");

  private com.google.gwt.user.client.ui.HorizontalPanel x = new com.google.gwt.user.client.ui.HorizontalPanel();
  private com.google.gwt.user.client.ui.Label x1 = new com.google.gwt.user.client.ui.Label();
  private com.google.gwt.user.client.ui.Label x2 = new com.google.gwt.user.client.ui.Label();
  private com.google.gwt.user.client.ui.VerticalPanel x3 = new com.google.gwt.user.client.ui.VerticalPanel();
  private com.google.gwt.user.client.ui.Label x4 = new com.google.gwt.user.client.ui.Label();
  private com.google.gwt.user.client.ui.TextArea x5 = new com.google.gwt.user.client.ui.TextArea();
  private com.google.gwt.user.client.ui.Label x6 = new com.google.gwt.user.client.ui.Label();
  private com.google.gwt.user.client.ui.TextArea x7 = new com.google.gwt.user.client.ui.TextArea();
  private com.google.gwt.user.client.ui.VerticalPanel x8 = new com.google.gwt.user.client.ui.VerticalPanel();
  private com.google.gwt.user.client.ui.Label x9 = new com.google.gwt.user.client.ui.Label();
  private com.google.gwt.user.client.ui.TextArea x10 = new com.google.gwt.user.client.ui.TextArea();
  private com.google.gwt.user.client.ui.Label x11 = new com.google.gwt.user.client.ui.Label();
  private com.google.gwt.user.client.ui.TextArea x12 = new com.google.gwt.user.client.ui.TextArea();
  public com.google.gwt.user.client.ui.HorizontalPanel getPanel() { return x; }

  public GWTCustomerWidgetFactory() {}

  public GWTCustomerWidgetFactory initialize(java.util.Map<String, Object> values)
  {
    x1.setText(text.get());
    x2.setText(text1.get());
    x4.setText(text2.get());
    x6.setText(text3.get());
    x9.setText(text4.get());
    x11.setText(text5.get());
    com.google.gwt.user.client.ui.TextArea c = x12;
    com.google.gwt.user.client.ui.Label c1 = x11;
    com.google.gwt.user.client.ui.TextArea c2 = x10;
    com.google.gwt.user.client.ui.Label c3 = x9;
    com.google.gwt.user.client.ui.VerticalPanel c4 = x8;
    com.google.gwt.user.client.ui.TextArea c5 = x7;
    com.google.gwt.user.client.ui.Label c6 = x6;
    com.google.gwt.user.client.ui.TextArea c7 = x5;
    com.google.gwt.user.client.ui.Label c8 = x4;
    com.google.gwt.user.client.ui.VerticalPanel c9 = x3;
    com.google.gwt.user.client.ui.Label c10 = x2;
    com.google.gwt.user.client.ui.Label c11 = x1;
    x8.add(c3);
    x3.add(c8);
    x.add(c11);
    x8.add(c2);
    x3.add(c7);
    x.add(c9);
    x8.add(c1);
    x3.add(c6);
    x.add(c10);
    x8.add(c);
    x.add(c4);
    x3.add(c5);
    return this;
  }
}
