package com.mycompany.client.hardcoded;

import com.hopstepjump.backbone.runtime.api.*;

/** generated by Evolve */
public class GWTCustomerWidgetFactory
{
  private Attribute<String> text = new Attribute<String>("<b>Enter full name</b>");
  private Attribute<String> text1 = new Attribute<String>("<b>Enter normal address</b>");

  private Attribute<String> title = new Attribute<String>("Customer details");
  private Attribute<String> text2 = new Attribute<String>("Enter billing address");
  private Attribute<String> text3 = new Attribute<String>("First:");
  private Attribute<String> text4 = new Attribute<String>("Last");
  private Attribute<String> text5 = new Attribute<String>("Street:");
  private Attribute<String> text6 = new Attribute<String>("Town:");

  private com.google.gwt.user.client.ui.HorizontalPanel h = new com.google.gwt.user.client.ui.HorizontalPanel();
  private com.mycompany.client.widgets.ButtonLogic l = new com.mycompany.client.widgets.ButtonLogic();
  private com.google.gwt.user.client.ui.Button b = new com.google.gwt.user.client.ui.Button();
  private com.mycompany.client.widgets.SimpleTabPanel d = new com.mycompany.client.widgets.SimpleTabPanel();
  private com.google.gwt.user.client.ui.VerticalPanel x = new com.google.gwt.user.client.ui.VerticalPanel();
  private com.google.gwt.user.client.ui.Label x1 = new com.google.gwt.user.client.ui.Label();
  private com.google.gwt.user.client.ui.TextBox x2 = new com.google.gwt.user.client.ui.TextBox();
  private com.google.gwt.user.client.ui.Label x3 = new com.google.gwt.user.client.ui.Label();
  private com.google.gwt.user.client.ui.TextBox x4 = new com.google.gwt.user.client.ui.TextBox();
  private com.google.gwt.user.client.ui.HTML x5 = new com.google.gwt.user.client.ui.HTML();
  private com.google.gwt.user.client.ui.VerticalPanel x6 = new com.google.gwt.user.client.ui.VerticalPanel();
  private com.google.gwt.user.client.ui.Label x7 = new com.google.gwt.user.client.ui.Label();
  private com.google.gwt.user.client.ui.TextBox x8 = new com.google.gwt.user.client.ui.TextBox();
  private com.google.gwt.user.client.ui.Label x9 = new com.google.gwt.user.client.ui.Label();
  private com.google.gwt.user.client.ui.TextBox x10 = new com.google.gwt.user.client.ui.TextBox();
  private com.google.gwt.user.client.ui.HTML x11 = new com.google.gwt.user.client.ui.HTML();
  private ICreate factory = new ICreate() {
    public Object create(java.util.Map<String, Object> values) {
      GWTAddressWidgetFactory f = new GWTAddressWidgetFactory();
      f.initialize(values);
      return f;
    }
    public void destroy(Object memento) {}
  };
  public com.google.gwt.user.client.ui.TabPanel getPanel() { return d; }

  public GWTCustomerWidgetFactory() {}

  public GWTCustomerWidgetFactory initialize(java.util.Map<String, Object> values)
  {
    h.setTitle(title.get());
    b.setText(text2.get());
    x1.setText(text3.get());
    x3.setText(text4.get());
    x5.setHTML(text.get());
    x7.setText(text5.get());
    x9.setText(text6.get());
    x11.setHTML(text1.get());
    com.hopstepjump.backbone.runtime.api.ICreate c = factory;
    com.google.gwt.user.client.ui.HTML c1 = x11;
    com.google.gwt.user.client.ui.TextBox c2 = x10;
    com.google.gwt.user.client.ui.Label c3 = x9;
    com.google.gwt.user.client.ui.TextBox c4 = x8;
    com.google.gwt.user.client.ui.Label c5 = x7;
    com.google.gwt.user.client.ui.VerticalPanel c6 = x6;
    com.google.gwt.user.client.ui.HTML c7 = x5;
    com.google.gwt.user.client.ui.TextBox c8 = x4;
    com.google.gwt.user.client.ui.Label c9 = x3;
    com.google.gwt.user.client.ui.TextBox c10 = x2;
    com.google.gwt.user.client.ui.Label c11 = x1;
    com.google.gwt.user.client.ui.VerticalPanel c12 = x;
    com.google.gwt.user.client.ui.HorizontalPanel c13 = h;
    com.google.gwt.user.client.ui.ClickListener c14 = l.getListener_ClickListener(com.google.gwt.user.client.ui.ClickListener.class);
    com.google.gwt.user.client.ui.ButtonBase c15 = b;
    x6.add(c1);
    x.add(c7);
    h.add(c12);
    d.addTitleTab(c13);
    x6.add(c5);
    h.add(c6);
    x.add(c11);
    x6.add(c4);
    x.add(c10);
    h.add(c15);
    x6.add(c3);
    x.add(c9);
    x6.add(c2);
    x.add(c8);
    l.setCreate_ICreate(c);
    b.addClickListener(c14);
    d.afterInit();
    return this;
  }
class GWTAddressWidgetFactory
{
  private Attribute<String> text7 = new Attribute<String>("<b>Enter billing address</b>");
  private Attribute<String> title1 = new Attribute<String>("Billing address");
  private Attribute<String> text8 = new Attribute<String>("Street:");
  private Attribute<String> text9 = new Attribute<String>("Town:");

  private com.google.gwt.user.client.ui.HorizontalPanel x26 = new com.google.gwt.user.client.ui.HorizontalPanel();
  private com.google.gwt.user.client.ui.VerticalPanel x27 = new com.google.gwt.user.client.ui.VerticalPanel();
  private com.google.gwt.user.client.ui.Label x28 = new com.google.gwt.user.client.ui.Label();
  private com.google.gwt.user.client.ui.TextBox x29 = new com.google.gwt.user.client.ui.TextBox();
  private com.google.gwt.user.client.ui.Label x30 = new com.google.gwt.user.client.ui.Label();
  private com.google.gwt.user.client.ui.TextBox x31 = new com.google.gwt.user.client.ui.TextBox();
  private com.google.gwt.user.client.ui.HTML x32 = new com.google.gwt.user.client.ui.HTML();

  public GWTAddressWidgetFactory() {}

  public GWTAddressWidgetFactory initialize(java.util.Map<String, Object> values)
  {
    x26.setTitle(title1.get());
    x28.setText(text8.get());
    x30.setText(text9.get());
    x32.setHTML(text7.get());
    com.google.gwt.user.client.ui.HTML c16 = x32;
    com.google.gwt.user.client.ui.TextBox c17 = x31;
    com.google.gwt.user.client.ui.Label c18 = x30;
    com.google.gwt.user.client.ui.TextBox c19 = x29;
    com.google.gwt.user.client.ui.Label c20 = x28;
    com.google.gwt.user.client.ui.VerticalPanel c21 = x27;
    com.google.gwt.user.client.ui.HorizontalPanel c22 = x26;
    x27.add(c16);
    x26.add(c21);
    x27.add(c20);
    d.addTitleTab(c22);
    x27.add(c19);
    x27.add(c18);
    x27.add(c17);
    return this;
  }
}
}
