package com.mycompany.client.hardcoded;

import com.hopstepjump.backbone.runtime.api.*;

/** generated by Evolve */
public class TwoButtonPanelFactory
{
  private Attribute<String> text = new Attribute<String>("Hello");
  private Attribute<String> title = new Attribute<String>("Tab1");
  private Attribute<String> text1 = new Attribute<String>("Goodbye");
  private Attribute<String> title1 = new Attribute<String>("Tab2");

  private com.google.gwt.user.client.ui.Button x = new com.google.gwt.user.client.ui.Button();
  private com.google.gwt.user.client.ui.Button x1 = new com.google.gwt.user.client.ui.Button();
  private com.mycompany.client.widgets.SimpleTabPanel x2 = new com.mycompany.client.widgets.SimpleTabPanel();
  public com.google.gwt.user.client.ui.TabPanel getPanel() { return x2; }

  public TwoButtonPanelFactory() {}

  public TwoButtonPanelFactory initialize(java.util.Map<String, Object> values)
  {
    x.setText(text.get());
    x.setTitle(title.get());
    x1.setText(text1.get());
    x1.setTitle(title1.get());
    com.google.gwt.user.client.ui.ButtonBase c = x1;
    com.google.gwt.user.client.ui.ButtonBase c1 = x;
    x2.addTitleTab(c1);
    x2.addTitleTab(c);
    x2.afterInit();
    return this;
  }
}
