package com.hopstepjump.deltaengine.base;

public enum ConstituentTypeEnum
{
  DELTA_PART,
  DELTA_ATTRIBUTE,
  DELTA_PORT,
  DELTA_CONNECTOR,
  DELTA_PORT_LINK,
  DELTA_OPERATION,
  DELTA_APPLIED_STEREOTYPE,
  DELTA_REQUIREMENT_FEATURE_LINK,
  DELTA_TRACE,
  DELTA_MISC
}
