/* Generated By:JavaCC: Do not edit this line. ZInternalParserConstants.java */
package edu.umd.cs.jazz.io;

public interface ZInternalParserConstants {

  int EOF = 0;
  int SINGLE_LINE_COMMENT = 7;
  int OBJECT = 9;
  int RETURN = 10;
  int APPDATA = 11;
  int BOOLEAN = 12;
  int BINARY = 13;
  int BYTE = 14;
  int CHAR = 15;
  int DOUBLE = 16;
  int FALSE = 17;
  int FLOAT = 18;
  int INT = 19;
  int LONG = 20;
  int NULL = 21;
  int SHORT = 22;
  int TRUE = 23;
  int INTEGER_LITERAL = 24;
  int DOUBLE_FLOATING_POINT_LITERAL = 25;
  int FLOATING_POINT_LITERAL = 26;
  int EXPONENT = 27;
  int CHARACTER_LITERAL = 28;
  int STRING_LITERAL = 29;
  int LBRACE = 30;
  int RBRACE = 31;
  int LBRACKET = 32;
  int RBRACKET = 33;
  int BUILT_IN_OBJECT_TYPE = 34;
  int IDENTIFIER = 35;
  int LETTER = 36;
  int DIGIT = 37;

  int DEFAULT = 0;
  int IN_SINGLE_LINE_COMMENT = 1;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "\"#\"",
    "<SINGLE_LINE_COMMENT>",
    "<token of kind 8>",
    "\"OBJECT\"",
    "\"RETURN\"",
    "\"PROLOG\"",
    "\"boolean\"",
    "\"BINARYDATAFOLLOWS\"",
    "\"byte\"",
    "\"char\"",
    "\"double\"",
    "\"false\"",
    "\"float\"",
    "\"int\"",
    "\"long\"",
    "\"null\"",
    "\"short\"",
    "\"true\"",
    "<INTEGER_LITERAL>",
    "<DOUBLE_FLOATING_POINT_LITERAL>",
    "<FLOATING_POINT_LITERAL>",
    "<EXPONENT>",
    "<CHARACTER_LITERAL>",
    "<STRING_LITERAL>",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "<BUILT_IN_OBJECT_TYPE>",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
    "\".\"",
  };

}
