package com.intrinsarc.states;

import com.intrinsarc.backbone.runtime.api.*;

/** generated by Evolve */
public class StatesExampleFactory implements IHardcodedFactory
{
  private java.util.List<IHardcodedFactory> children;

  // attributes
  private java.util.Date purchasedWhen;
  private java.lang.String model;
  private java.lang.String renterName;

  // connectors
  private com.intrinsarc.states.IRentalEvent c;
  private com.intrinsarc.states.IRentalEvent c1;
  private com.intrinsarc.backbone.runtime.api.ITerminal c2;
  private com.intrinsarc.backbone.runtime.api.ITransition c3;
  private com.intrinsarc.backbone.runtime.api.ITransition c4;
  private com.intrinsarc.backbone.runtime.api.ITransition c5;
  private com.intrinsarc.states.IRentalEvent c6;
  private com.intrinsarc.states.IRentalEvent c7;
  private com.intrinsarc.base.IRentalCarDetails c8;

 // parts
  private com.intrinsarc.states.StatesExampleRunner x10 = new com.intrinsarc.states.StatesExampleRunner();
  private com.intrinsarc.base.RentalCarDetails x7 = new com.intrinsarc.base.RentalCarDetails();
  private com.intrinsarc.backbone.runtime.implementation.Terminal x2 = new com.intrinsarc.backbone.runtime.implementation.Terminal();
  private com.intrinsarc.states.Rented r = new com.intrinsarc.states.Rented();
  private com.intrinsarc.states.Available a = new com.intrinsarc.states.Available();
  private com.intrinsarc.backbone.runtime.implementation.StateDispatcher dispatcher = new com.intrinsarc.backbone.runtime.implementation.StateDispatcher();
  public com.intrinsarc.backbone.runtime.api.IRun getRun() { return x10; }

  public StatesExampleFactory() {}

  public StatesExampleFactory initialize(IHardcodedFactory parent, java.util.Map<String, Object> values)
  {
    purchasedWhen = new java.util.Date(108, 10, 10);
    model = "Volvo";
    renterName = null;
    x7.setPurchased(purchasedWhen);
    x7.setModel(model);
    r.setRenterName(renterName);
    c = a;
    c1 = r;
    c2 = x2;
    c3 = a.getIn_Provided();
    c4 = r.getIn_Provided();
    c5 = a.getIn_Provided();
    c6 = (com.intrinsarc.states.IRentalEvent) dispatcher.getDEvents_Provided(com.intrinsarc.states.IRentalEvent.class);
    c7 = (com.intrinsarc.states.IRentalEvent) dispatcher.getDEvents_Provided(com.intrinsarc.states.IRentalEvent.class);
    c8 = x7;
    dispatcher.addDDispatch(c);
    dispatcher.addDDispatch(c1);
    dispatcher.setDStart(c2);
    x2.setOut(c3);
    a.setOut(c4);
    r.setOut(c5);
    x7.setRenter(c6);
    x10.addRentalState(c7);
    x10.addCar(c8);
    return this;
  }
  public void childDestroyed(IHardcodedFactory child) { children.remove(child); }

  public void destroy()
  {
  }

  static void destroyChildren(IHardcodedFactory parent, IHardcodedFactory me, java.util.List<IHardcodedFactory> children)
  {
    parent.childDestroyed(me);
    if (children != null) {
      java.util.List<IHardcodedFactory> copy = new java.util.ArrayList<IHardcodedFactory>(children);
      java.util.Collections.reverse(copy);
      for (IHardcodedFactory f : copy)
        f.destroy();
    }
  }
}
