package com.intrinsarc.states;

import com.intrinsarc.backbone.runtime.api.*;

/** generated by Evolve */
public class StatesExampleFactory implements IHardcodedFactory
{
  private java.util.List<IHardcodedFactory> children;

  // attributes
  private java.util.Date purchasedWhen;
  private java.lang.String model;
  private java.lang.String renterName;

  // connectors
  private com.intrinsarc.states.IRentalEvent c;
  private com.intrinsarc.states.IRentalEvent c1;
  private com.intrinsarc.backbone.runtime.api.ITerminal c2;
  private com.intrinsarc.backbone.runtime.api.ITransition c3;
  private com.intrinsarc.backbone.runtime.api.ITransition c4;
  private com.intrinsarc.backbone.runtime.api.ITransition c5;
  private com.intrinsarc.states.IRentalEvent c6;
  private com.intrinsarc.states.IRentalEvent c7;
  private com.intrinsarc.base.IRentalCarDetails c8;

 // parts
  private com.intrinsarc.states.StatesExampleRunner x10 = new com.intrinsarc.states.StatesExampleRunner();
  private com.intrinsarc.base.RentalCarDetails x7 = new com.intrinsarc.base.RentalCarDetails();
  private com.intrinsarc.backbone.runtime.implementation.Terminal x2 = new com.intrinsarc.backbone.runtime.implementation.Terminal();
  private com.intrinsarc.states.Rented r = new com.intrinsarc.states.Rented();
  private com.intrinsarc.states.Available a = new com.intrinsarc.states.Available();
  private com.intrinsarc.backbone.runtime.implementation.StateDispatcher dispatcher = new com.intrinsarc.backbone.runtime.implementation.StateDispatcher();
  public com.intrinsarc.backbone.runtime.api.IRun getRun() { return x10.getRun_IRun(null); }

  public StatesExampleFactory() {}

  public StatesExampleFactory initialize(IHardcodedFactory parent, java.util.Map<String, Object> values)
  {
    purchasedWhen = new java.util.Date(108, 10, 10);
    model = "Volvo";
    renterName = null;
    x7.setModel(model);
    x7.setPurchased(purchasedWhen);
    r.setRenterName(renterName);
    c = a.getEvents_IRentalEvent(com.intrinsarc.states.IRentalEvent.class);
    c1 = r.getEvents_IRentalEvent(com.intrinsarc.states.IRentalEvent.class);
    c2 = x2.getStartTerminal_ITerminal(com.intrinsarc.backbone.runtime.api.ITerminal.class);
    c3 = a.getIn_ITransition(com.intrinsarc.backbone.runtime.api.ITransition.class);
    c4 = r.getIn_ITransition(com.intrinsarc.backbone.runtime.api.ITransition.class);
    c5 = a.getIn_ITransition(com.intrinsarc.backbone.runtime.api.ITransition.class);
    c6 = (com.intrinsarc.states.IRentalEvent) dispatcher.getDEvents_IEvent(com.intrinsarc.states.IRentalEvent.class);
    c7 = (com.intrinsarc.states.IRentalEvent) dispatcher.getDEvents_IEvent(com.intrinsarc.states.IRentalEvent.class);
    c8 = x7.getDetails_IRentalCarDetails(com.intrinsarc.base.IRentalCarDetails.class);
    dispatcher.setDDispatch_IEvent(c, -1);
    dispatcher.setDDispatch_IEvent(c1, -1);
    dispatcher.setDStart_ITerminal(c2);
    x2.setOut_ITransition(c3);
    a.setOut_ITransition(c4);
    r.setOut_ITransition(c5);
    x7.setRenter_IRenterDetails(c6);
    x10.setRentalStates_IRentalEvent(c7, -1);
    x10.setCars_IRentalCarDetails(c8, -1);
    return this;
  }
  public void childDestroyed(IHardcodedFactory child) { children.remove(child); }

  public void destroy()
  {
  }

  static void destroyChildren(IHardcodedFactory parent, IHardcodedFactory me, java.util.List<IHardcodedFactory> children)
  {
    parent.childDestroyed(me);
    if (children != null) {
      java.util.List<IHardcodedFactory> copy = new java.util.ArrayList<IHardcodedFactory>(children);
      java.util.Collections.reverse(copy);
      for (IHardcodedFactory f : copy)
        f.destroy();
    }
  }
}
